- capdl-loader-app/src/main.c
Before this change, the badge field of a notification capability bound to an IRQ was ignored by capdl-loader-app.
After this change, if a notification with a non-zero badge is bound to a IRQ, a badged capability is minted and used.
> capdl-loader-app: apply irq notification badge

- cdl_utils/capdl_linker.py
Good day,
currently, every time the linker is invoked when running from [the Docker setup](https://docs.sel4.systems/projects/dockerfiles/) it prints a syntax warning [0]. This is a bit jarring and easily avoided.
In this case we are just comparing against a string and don't actually want to check the identity. Basically, `==` is for comparing values and `is` is for comparing identities. It just happens to work in Python either way as strings are immutable.
[0]
```
$ ninja
[3/8] Generating spec.cdl
/host/projects/capdl/cdl_utils/capdl_linker.py:113: SyntaxWarning: "is" with a literal. Did you mean "=="?
if args.which is "build_cnode":
/host/projects/capdl/cdl_utils/capdl_linker.py:122: SyntaxWarning: "is" with a literal. Did you mean "=="?
if args.which is "gen_cdl":
[4/8] Generate CPIO …
```
> Trivial: Fix Python syntax warnings when capdl_linker.py is invoked

- capdl-loader-app/README.md
The old link no longer works and this causes the automatic commit checks
to fail
Signed-off-by: Axel Heider <axelheider@gmx.de>
> capdl-loader-app: fix link in readme

- capdl-loader-app/README.md
- capdl-loader-app/helpers.cmake
Make PLATFORM_SIFT agnostic of the build system directory layout
Note that this patch is on top of https://github.com/seL4/capdl/pull/15, if this get's merged the other PR #15 is obsolete.
> cmake: use SEL4_CMAKE_TOOL_DIR for PLATFORM_SIFT

- capdl-loader-app/src/main.c
Make the log output a bit nicer
* Use log level INFO for CapDL Loader's start/end message and mention explicitly, that this is the CapDL loader. This turned out to be quite useful in various test cases, as it give some nice messages to check for when trying to determine if the system startup worked well at least. Having this at the INFO level allows the same mechanisms to work still for build with reduced log output.
* Move printing a message about the used capability slots to the init_system function. It seems to be better placed there and this keeps the main function slim. 
**Question**: is printing the number of use slot something that should be INFO also? We had some issues where the slots were almost exhausted and then it depends on each build's memory layout if the system fits in or …
> capdl-loader-app: improve log output

- capdl-loader-app/README.md
- capdl-loader-app/src/main.c
The recent library updates add the const qualifiers where possible, so we have to add it here also to avoid compiler warnings.
See
- https://github.com/seL4/util_libs/pull/73
- https://github.com/seL4/seL4_libs/pull/29
> capdl-loader-app: add const qualifier

- capdl-loader-app/src/main.c
The compiler can't tell that some code is dead under rv32 and emits a
-Wshift-count-overflow warning. Use the preprocessor to remove the
unused code when the page table hierarchy won't use it.
Fixes: https://github.com/seL4/capdl/issues/24
> capdl-loader-app: Suppress rv32 overflow warning

- capdl-loader-app/src/main.c
- python-capdl-tool/capdl/Allocator.py
This PR has two commits, both centered around the RT Kernel.
1st, it allows CAmkES uses to set components and threads to secondary cores using the built-in `.affinity` method.
2nd, it fixes a python bug that always printed out a scheduling control cap as Core 0. This prints properly in the `.cdl`; however, the actual cdl -> c array translation using Haskell still always assigns the capability to the default core, because the `PrintC.hs` file doesn't use the passed in core parameter.
I fixed this (grossly) by doing:
```
+showCap _ (SchedControlCap core) _ _ _ =
+    "{.type = CDL_SchedControlCap, .core = " ++ show core ++ "}"
```
And adding `unsigned core` to the `CDL_Cap` structure in `capdl.h`. This allowed me to reference the core in `CDL_SchedControl_Core` with `return …
> Fixes for RT Kernel

- cdl_utils/capdl_linker.py
simpleeval is no longer maintained. As the python setuptool has dropped
python 2 support completely, it is unable to install simpleeval from
source. Replacing it with the builtin eval(). It only takes input from
camkes template, which is somewhat trusted. Simple sanity check is also
added to filter out unexpected inputs.
Signed-off-by: Siwei Zhuang <siwei.zhuang@unsw.edu.au>
> cdl_utils: remove unmaintained python library

- .github/workflows/build.yml
- cdl_utils/untyped_gen.py
These are needed for the more recent python install in the new docker environment.
- PyYAML > 5.1 requires a loader argument
- make sure GitHub tests use at most python 3.9 (as in docker container). Python 3.10 doesn't work, because `nose` breaks.
> cdl_utils: provide yaml loader

- cdl_utils/capdl_linker.py
- cdl_utils/untyped_gen.py
The previous commit missed a spot and managed to misspell the argument.
> cdl_utils: more PyYaml adjustments

- capDL-tool/CapDL/AST.hs
- capDL-tool/CapDL/MakeModel.hs
These cases were previously comparing against lists of parameters of the incorrect size. Luckily, the lists being created were all accidentally too large, which means that the validation step was just being too permissive.
> capDL-tool: fix several cases in validObjPars 

- python-capdl-tool/capdl/util.py
Follow up from discussion https://github.com/seL4/capdl/pull/39, a bit of cleanup and documentation as minimal take-aways:
- doc: clarify "arm11" usage despite ARMv6
- python: unify architecture dictionaries[](https://github.com/axel-h) 
- avoid redundancy and merge this into one dict.
- remove internal helper normalise_architecture()
> Cleanup and clarify "arm11" usage despite ARMv6 removal 

- capdl-loader-app/src/main.c
Align with recent changes that expect page alignment.
See https://github.com/seL4/seL4_libs/pull/63
It seems the heap is never used, so we could also consider removing it completely. I'm only running into issues if I add more alignment checks in the heap management. Thus adding the alignment here seems a good choice.
> capdl-loader-app: ensure heap is aligned

- capdl-loader-app/include/capdl.h
- capdl-loader-app/src/main.c
- python-capdl-tool/capdl/Object.py
This updates the python-capdl-tool and capdl-loader-app to support specifying the rights for fault handler caps on realtime systems.
The python-capdl-tool defaults to seL4_AllRights, which results in the same behaviour as before.
> Support specifying rights for fault handler caps

- capDL-tool/capDL-tool.cabal
- capDL-tool/stack.yaml
This is in preparation of updating the docker containers to a more recent GHC version for better Linux/aarch64/v8 support.
> capDL-tool: update to LTS Haskell 20.25, ghc-9.2.8

- object_sizes/object_sizes.yaml
Some definitions that object_sizes depends on are now found in a deprecated.h header file.
Because object_sizes generates a yaml file, it can't only include <sel4/sel4.h> because of incompatible C source definitions.
> object_sizes: Add include for deprecated constants

- capdl-loader-app/include/capdl.h
The aarch64 vspace API is changed to only have a single pagetable object and capability type for all intermediate page table levels. The root vspace object is still a separate object and capability type.
As part of this change, seL4_ARM_PageGlobalDirectoryObject is no longer defined for configurations where it was previously an invalid object. This causes some minor breakages which this commit addresses.
> aarch64: Minimal update for vspace API change

- .github/workflows/build.yml
- python-capdl-tool/requirements.txt
- python-capdl-tool/tests/__init__.py
- python-capdl-tool/tests/allocator.py
- python-capdl-tool/tests/runall.py
- python-capdl-tool/tests/testelf.py
- python-capdl-tool/tests/testmerge.py
.github action runners can just run tests with python3 only now.
Addresses https://github.com/seL4/capdl/issues/31
> python-capdl-tool: Update python3 test scripts

- .github/workflows/build.yml
Update to current node16 versions. The old node12 actions are deprecated and will stop working.
> github: bump GitHub action versions

- .github/workflows/build.yml
https://github.com/seL4/capdl/pull/55 did most of what this PR initially tried to do. What is left is:
- switch to official Haskell action for stack/ghc setup
- explicitly add python 3.9 to the test, because that's the version in docker (but keep 3.x, i.e. latest python)
> upgrade GH actions + test python 3.9 in addition to latest python

- .github/workflows/build.yml
GitHub has started issuing warnings for node16 actions.
> github: bump actions to node20

- python-capdl-tool/capdl/ELF.py
This is a trivial change, for the sake of code clarity.
> python-capdl-tool: Remove redundant assignment

- CHANGES.md
- capDL-tool/CapDL/Model.hs
- capDL-tool/CapDL/ParserUtils.hs
- capDL-tool/CapDL/State.hs
- capDL-tool/tools/capdl.vim
- capdl-loader-app/include/capdl.h
- capdl-loader-app/src/main.c
This will be required by [Microkit](https://github.com/seL4/microkit).
> capDL-tool, capdl-loader-app: Add support for binding notifications for TCBs

- capdl-loader-app/include/capdl.h
- capdl-loader-app/src/main.c
https://github.com/seL4/capdl/pull/12 (authored by me - sorry) introduced an inconsistency in macro capitalization in `capdl-loader-app`. This trivial change corrects it.
> trivial: Make capitalization more consistent

- CHANGES.md
- cdl_utils/untyped_gen.py
We only need the yaml part, and `pyaml` (Pretty Yaml) has been removed from sel4-deps in sel4-deps 0.4.0. Instead sel4-deps now has `pyyaml`, which only provides the `yaml` import.
> undyped_gen: remove pyaml dependency
